### ISSUE TITLE
The button to generate PDF does not appear

### ISSUE THREAD

**Issue by U17205367** [arthur-mdn/ExportGrafanaDashboardToPDF#3]
I don't know what I'm doing wrong but I can't get the "Export to PDF" button to appear when I click on the "Share" option on a dashboard. I did the steps you mentioned and if I try to generate a PDF via cURL or shell script it works perfectly.

What I'm doing is adding a visualization to the dashboard, I select "text" and change from markdown to html and paste the content of the file "grafana-button.html" I apply it and then save the dashboard but it doesn't appear. I've already tried changing pdfGenerationServerUrl to my public IP, private IP and even the container IP but I can't get it to work.

I've changed the disable_sanitize_html property to true and I'm using grafana 11.2 in docker

**Comment by U17205367** [comment]
I was reviewing the code for grafana-button.html and I see that it looks for a modal called shareModalContent and after finding it it looks for an attribute called aria-label="Tab Link" which does not exist on my dashboard. I have tried 2 dashboards and the name of the modal is css-1y5q12f-modalHeader and the aria-label does not exist, perhaps that is why I cannot see the "Export to PDF" button.

**Comment by arthur-mdn** [comment]
Hello,
Thank you for your issue submission !
Can you please try this steps to help debugging the issue :

- On your dashboard page, open the share modal by clicking on the share button.
![image](https://github.com/user-attachments/assets/fedab59d-15f8-41c3-abe4-260325006c80)

- Once the share modal is open, please execute this in your browser console : 
```js
document.querySelectorAll('div[class*="shareModalContent"], div[role="dialog"], div[role="tablist"] button').forEach((button)=>{
	console.log(button.getAttribute("aria-label"))
});
```

- Tell me what content you have
![image](https://github.com/user-attachments/assets/b6defbf0-e9c4-48e1-bc28-add102e93f10)

**Comment by U17205367** [comment]
Hello Arthur thanks for your response, I have executed what was sent in two grafanas installed on completely different servers, both are in a docker container. The curious thing is that in one the expected result is obtained and in the other one it is not.

Grafana v11.2.0

![image](https://github.com/user-attachments/assets/8f72c6d3-32c4-4578-be6c-b00c88bad1fb)

Grafana v11.0.0

![image](https://github.com/user-attachments/assets/f6b3c313-4c01-4120-94a2-c107c380701b)

**Comment by arthur-mdn** [comment]
There were changes in the HTML structure across different versions, which made the querySelector incompatible with Grafana v11.2.0. I’ve updated it to correctly detect the shareModal.

Please test the updated `grafana-button.html` file and let me know how it works for you!

**Comment by U17205367** [comment]
I just tried it and it works very well with Grafana 11.2.0. Now I have two small problems that I know are not the root of the main problem, but you tell me if I need to open another issue

1.- It generates the PDF report but I have 2 visualizations where the query is somewhat heavy, which is why it takes between 15 and 30 seconds to load the information depending on the time range I choose, so in the PDF that part comes out blank. Is there a way I can validate that all the visualizations have actually loaded before generating the PDF?

![image](https://github.com/user-attachments/assets/1a3e4670-0f19-4a0b-bc6f-9c782042b1a3)

2.- In my dashboard I have the America/Latin UTC-5 time zone configured, but when I generate the PDF the times come out in UTC format. Is there a variable where I can modify this?

![image](https://github.com/user-attachments/assets/d370ea86-a64e-49fe-a80e-583df6df9e21)

Thank you in advance for your attention

**Comment by arthur-mdn** [comment]
Thank you for testing it out! 
Since both of these issues require additional development, please open separate issues for each one. 
I'll take care of them as soon as possible !
